from django.db import models
from neomodel import StructuredNode, StringProperty, IntegerProperty, RelationshipTo, RelationshipFrom, Relationship

class Category(StructuredNode):
    name = StringProperty()
    text = StringProperty()
    relationship = RelationshipFrom("Entity", "BELONGS_TO")

class Entity(StructuredNode):
    name = StringProperty()
    text = StringProperty()
    relationship = RelationshipTo("Category", "BELONGS_TO")  
    relationship_entity = RelationshipTo("Entity", "BELONGS_TO") 
    relationship_GeoEra = RelationshipTo("GeoEra", "APPEARED_DURING") 
    relationship_GeoPeriod = RelationshipTo("GeoPeriod", "APPEARED_DURING") 
    
class GeoPeriod(StructuredNode):
    name = StringProperty()
    start = IntegerProperty()
    end = StringProperty()
    text = StringProperty() 
    relationship = RelationshipTo("GeologicalPeriod", "PART_OF")    
    relationship_appeared = RelationshipTo("GeoEra", "APPEARED_DURING")
    relationship_belongs = RelationshipFrom("Entity", "BELONGS_TO")
    
class GeoEra(StructuredNode):
    name = StringProperty()
    start = IntegerProperty()
    end = StringProperty()
    text = StringProperty() 
    relationship = RelationshipTo("GeoEonEra", "PART_OF") 
    relationship_appeared = RelationshipFrom("GeoPeriod", "APPEARED_DURING") 
    relationship_belongs = RelationshipFrom("Entity", "BELONGS_TO")
     
class GeoEonEra(StructuredNode):
    name = StringProperty()
    text = StringProperty() 
    relationship = RelationshipFrom("GeoEra", "PART_OF")
    
class GeologicalPeriod(StructuredNode):
    name = StringProperty()
    text = StringProperty() 
    relationship = RelationshipFrom("GeoPeriod", "PART_OF")
    
class Археи(StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Порядок = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")

class Бактерии(StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Порядок = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")

class Грибы(StructuredNode):
    name = StringProperty()
    text = StringProperty()
    image_url = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Порядок = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Отдел = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")

class Зеленые_водоросли(StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Порядок = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Отдел = StringProperty()
    Царство = StringProperty() 
    relationship = RelationshipTo("Entity", "BELONGS_TO") 
    
class Саговниковидные(StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отдел = StringProperty()
    Порядок = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO") 
    
class Гинкговидные (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отдел = StringProperty()
    Порядок = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")

class Хвойные (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отдел = StringProperty()
    Порядок = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")

class Гнетовидные (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отдел = StringProperty()
    Порядок = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Царство = StringProperty()  
    relationship = RelationshipTo("Entity", "BELONGS_TO")

class Хвощевидные (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отдел = StringProperty()
    Порядок = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Царство = StringProperty() 
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Плауновидные (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отдел = StringProperty()
    Порядок = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Царство = StringProperty() 
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Моховидные (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отдел = StringProperty()
    Порядок = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Царство = StringProperty() 
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Папоротниковидные (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отдел = StringProperty()
    Порядок = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Царство = StringProperty()  
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Цветковые (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отдел = StringProperty()
    Порядок = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Малощетниковые (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отряд = StringProperty()
    Порядок = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Многощетниковые (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отряд = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Круглые_черви (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отряд = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Губки (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отряд = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Инфузории (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отряд = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Брюхоногие (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отряд = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Ленточные_черви (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отряд = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Морские_ежи (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отряд = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Двустворчатые (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отряд = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Сосальщики (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отряд = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Костные (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отряд = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Хрящевые (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отряд = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Морские_лилии (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отряд = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")

class Морские_звезды (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отряд = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")
       
class Головоногие (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отряд = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Ракообразные (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отряд = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Насекомые (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отряд = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Паукообразные (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отряд = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")
    
class Приматы (StructuredNode):
    name = StringProperty()
    text = StringProperty()
    Вид = StringProperty()
    Класс = StringProperty()
    Отряд = StringProperty()
    Род = StringProperty()
    Семейство = StringProperty()
    Тип = StringProperty()
    Царство = StringProperty()
    relationship = RelationshipTo("Entity", "BELONGS_TO")





